[package]
name = "ahrs_gazebo"
version = "0.1.0"
edition = "2024"

[dependencies]
estima = { git = "https://github.com/copterust/estima.git", branch = "main" }
gz = "0.9.0"
nalgebra = "0.33.2"
tokio = { version = "1.37.0", features = ["full"] }
